export interface ProductSheet{
    categorie: string,
    condition_: string,
    description: string,
    etat: string,
    id: number,
    id_categorie: number,
    id_condition: number,
    id_etat: number,
    id_pays: number,
    id_utilisateur: number,
    id_ville: number,
    pays: string,
    prix: number,
    titre: string,
    utilisateur: string,
    ville: string,
}